baseURL = 'https://dudung.github.io/bytes-and-grains'
languageCode = 'en-us'
title = 'bytes-and-grains'
theme = 'default'

enableEmoji = true

#disableKinds = ["taxonomyTerm"]

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"


[[menu.main]]
  name = 'Home'
  weight = 1
  identifier = 'home'
  url = '/'
