baseURL = 'https://dudung.github.io/bug'
languageCode = 'en-us'
title = 'bytes-und-grains'
theme = 'default'

enableEmoji = true

#disableKinds = ["taxonomyTerm"]

# 20240805 an der Uni
ignoreErrors = ['error-missing-instagram-accesstoken']

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"


[[menu.main]]
  name = 'Home'
  weight = 1
  identifier = 'home'
  url = '/'

